export const services = [
  {
    id: "svc-crisis-line",
    slug: "crisis-line",
    category: "crisis_line",
    name: "Crisis Line",
    summary: "Support for people who need help right now.",
    description: "[PLACEHOLDER] General information about Haven House's crisis line goes here. This page describes what kind of help is available and how it works — it is not itself a crisis line.",
    howToAccess: "[PLACEHOLDER] Describe how someone accesses this service — phone, drop-in, referral, hours.",
    isPublished: true,
  },
  {
    id: "svc-accommodation",
    slug: "accommodation",
    category: "accommodation",
    name: "Accommodation",
    summary: "Short-term, safe places to stay for people who need them.",
    description: "[PLACEHOLDER] General information about accommodation support goes here.",
    howToAccess: "[PLACEHOLDER] How to access this service.",
    isPublished: true,
  },
  {
    id: "svc-psychological-support",
    slug: "psychological-support",
    category: "psychological_support",
    name: "Psychological Support",
    summary: "Connecting people with mental health support and services.",
    description: "[PLACEHOLDER] General information about psychological support goes here. This service does not provide diagnosis, therapy, or clinical advice itself.",
    howToAccess: "[PLACEHOLDER] How to access this service.",
    isPublished: true,
  },
  {
    id: "svc-ndis",
    slug: "ndis",
    category: "ndis",
    name: "NDIS Services",
    summary: "Support connected to the National Disability Insurance Scheme.",
    description: "[PLACEHOLDER] General information about NDIS-related services goes here.",
    howToAccess: "[PLACEHOLDER] How to access this service.",
    isPublished: true,
  },
  {
    id: "svc-hh-kids",
    slug: "hh-kids",
    category: "hh_kids",
    name: "HH Kids",
    summary: "Programs and support for children and families.",
    description: "[PLACEHOLDER] General information about HH Kids goes here.",
    howToAccess: "[PLACEHOLDER] How to access this service.",
    isPublished: true,
  },
  {
    id: "svc-chaplaincy",
    slug: "chaplaincy",
    category: "chaplaincy",
    name: "Chaplaincy",
    summary: "Pastoral care and support, open to people of all beliefs and none.",
    description: "[PLACEHOLDER] General information about chaplaincy support goes here.",
    howToAccess: "[PLACEHOLDER] How to access this service.",
    isPublished: true,
  },
  {
    id: "svc-jobs-program",
    slug: "jobs-program",
    category: "jobs_program",
    name: "Jobs Program",
    summary: "Help with finding and keeping work.",
    description: "[PLACEHOLDER] General information about the jobs program goes here.",
    howToAccess: "[PLACEHOLDER] How to access this service.",
    isPublished: true,
  },
  {
    id: "svc-antisemitism-resources",
    slug: "antisemitism-resources",
    category: "antisemitism_resources",
    name: "Antisemitism Resources",
    summary: "Support and resources for people affected by antisemitism.",
    description: "[PLACEHOLDER] General information about this support and resources goes here.",
    howToAccess: "[PLACEHOLDER] How to access this service.",
    isPublished: true,
  },
  {
    id: "svc-social-work",
    slug: "social-work",
    category: "social_work",
    name: "Social Work",
    summary: "General social work support and referrals.",
    description: "[PLACEHOLDER] General information about social work support goes here.",
    howToAccess: "[PLACEHOLDER] How to access this service.",
    isPublished: true,
  },
];

export function getServiceBySlug(slug) {
  return services.find((s) => s.slug === slug && s.isPublished);
}

export function getPublishedServices() {
  return services.filter((s) => s.isPublished);
}