import { siteConfig } from "@/lib/siteConfig";

// Static, reused on every page. This copy is deliberately NOT generated by
// the chatbot or any dynamic logic — it is the one fixed, always-correct
// safety message on the site.
export default function CrisisBanner() {
  return (
    <div className="crisis-banner" role="note" aria-label="Crisis contact information">
      <div className="crisis-banner__inner">
        <span aria-hidden="true">●</span>
        <span>
          If you or someone else is in immediate danger, call{" "}
          <a href={`tel:${siteConfig.emergencyNumber}`}>{siteConfig.emergencyNumber}</a>. For 24/7
          crisis support, call{" "}
          <a href={`tel:${siteConfig.crisisNumber}`}>
            <strong>{siteConfig.crisisNumber}</strong>
          </a>
          .
        </span>
      </div>
    </div>
  );
}
